name: Events demo 1
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - "dev-*"
      - "feat/**"
    paths-ignore:
      - ".github/workflows/*"
jobs:
  deploy:
    runs-on: ubuntu-lates
    steps:
      - name: Output event data
        run: echo "${{ toJson(github.event) }}"
      - name: Get code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..."
