name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        default: dist
        type: string
        description: "Name of the artifact to download"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Output Information
        run: echo "Deploying & uploading..."
