name: Reusable Workflow
on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        default: dist
        type: string
        description: "Name of the artifact to download"
    # secrets:
    #   some-secret:
    #     required: true
    outputs:
      result:
        description: "The outcome of the deployment step"
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v5
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Output Information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: set-result
        run: echo "step-result::sucess" >> $GITHUB_OUTPUT
